name: Build CopilotOS GSI

on:
  push:
    branches:
      - android-14.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Repo
      run: |
        mkdir -p ~/bin
        PATH=~/bin:$PATH
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo

    - name: Initialize PixelOS source
      run: |
        mkdir pixelos
        cd pixelos
        repo init -u https://github.com/PixelOS-AOSP/manifest.git -b thirteen
        repo sync

    - name: Set up build environment
      run: |
        sudo apt-get update && sudo apt-get install -y openjdk-8-jdk git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip

    - name: Build GSI
      run: |
        source build/envsetup.sh
        lunch aosp_arm64-userdebug
        make -j$(nproc --all) systemimage

    - name: Upload GSI
      uses: actions/upload-artifact@v2
      with:
        name: CopilotOS-GSI
        path: out/target/product/*/system.img

    - name: Prepare OTA update
      run: |
        # Add your OTA update script here

    - name: Include Google services
      run: |
        # Add your script to include Google services here
        
